// module.exports = {
//   presets: ['module:@react-native/babel-preset'],
//   plugins: [
//     [
//       'module-resolver',
//       {
//         root: ['./src/'],
//         alias: {
//           '~images': './src/asset/images',
//           '~icons': './src/asset/icons',
//           '~fonts': './src/asset/fonts',
//           '~jsons': './src/asset/jsons',
//           '~components': './src/components',
//           '~constants': './src/constants',
//           '~hooks': './src/hooks',
//           '~navigators': './src/navigators',
//           '~screens': './src/screens',
//           '~services': './src/services',
//           '~reducers': './src/stores/reducers',
//           '~store': './src/stores/store',
//           '~styles': './src/styles',
//           '~theme': './src/theme',
//           '~utils': './src/utils',
//           '~': './src',
//         },
//         extensions: [
//           '.js',
//           '.jsx',
//           '.ts',
//           '.tsx',
//           '.json',
//           '.android.js',
//           '.android.jsx',
//           '.android.ts',
//           '.android.tsx',
//           '.ios.js',
//           '.ios.jsx',
//           '.ios.ts',
//           '.ios.tsx',
//           '.native.js',
//           '.native.jsx',
//           '.native.ts',
//           '.native.tsx',
//         ],
//       },
//     ],
//   ],
// };
const moduleResolver = [
  {
    root: ['./src/'],
    alias: {
      '~images': './src/asset/images',
      '~icons': './src/asset/icons',
      '~fonts': './src/asset/fonts',
      '~jsons': './src/asset/jsons',
      '~components': './src/components',
      '~constants': './src/constants',
      '~hooks': './src/hooks',
      '~navigators': './src/navigators',
      '~screens': './src/screens',
      '~services': './src/services',
      '~reducers': './src/stores/reducers',
      '~store': './src/stores/store',
      '~styles': './src/styles',
      '~theme': './src/theme',
      '~utils': './src/utils',
      '~': './src',
    },
    extensions: [
      '.js',
      '.jsx',
      '.ts',
      '.tsx',
      '.json',
      '.android.js',
      '.android.jsx',
      '.android.ts',
      '.android.tsx',
      '.ios.js',
      '.ios.jsx',
      '.ios.ts',
      '.ios.tsx',
      '.native.js',
      '.native.jsx',
      '.native.ts',
      '.native.tsx',
    ],
  },
];

module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    moduleResolver,
    'transform-remove-console',
    'react-native-paper/babel',
    'react-native-reanimated/plugin',
  ],
};
