export const strings = {
  ko: {
    registerStudy: {
      benefit: '베네핏 소개',
      subscribe: '구독하기',
      recommendBuy: '플랜 구성에 따라 구독하실 수 있습니다.',
      isFirstBuy: '무료 체험 시작 및 구독',
    },
    registerStudyStep2: {
      register: '구독중',
      noteStudy: '대회가 진행되지 않을 때도 학습할 수 있습니다.',
      notifyDelete: '정기 구독 해지 안내',
      standardIOS: '- iOS 기준: 설정 > 계정 > 구독 > 구독취소',
      standardAndroid: '- 안드로이드 기준 : 설정 > 결제 및 정기결제 > 구독 취소',
    },
    errorText: {
      IDIsNotFormat: '아이디는 영문, 영문+숫자를 포함한 6~16자 이내로 만들어주세요.',
      emailIsNotFormat: '올바른 이메일 주소 형식이 아닙니다.',
      passwordIsNotFormat: '영문, 숫자, 특수문자를 조합하여 최소 8자리 이상 입력하세요.',
      passwordIsFormat: '2~10자 이내 국문/영문/숫자로 입력해주세요.',
      confirmPasswordIsNotMatch: '입력한 비밀번호와 일치하지 않습니다.',
      passwordIsMatchNewPassword: '기존 비밀번호를 새 비밀번호로 재사용하실 수 없습니다.',
      confirmPasswordIsMatchPassword: '사용 가능한 비밀번호 입니다',
      nicknameIsNotFormat:
        '닉네임에는 -, _, .을 제외한 특수문자를 사용할 수 없습니다. (공백 사용 불가)',
      nicknameIsNotTrue: '닉네임은 국문, 영문, 숫자를 사용해 2~10자 이내로 만들어주세요.',
      emailNotFormat: '올바른 이메일 주소 형식이 아닙니다.',
      idAlreadyExists: '이미 사용중인 아이디입니다.',
      emailAlreadyExists: '이미 사용중인 이메일 주소입니다.',
      nicknameAlreadyExists: '이미 사용중인 닉네임입니다.',
      nicknameIsMatch: '사용 가능한 닉네임 입니다',
      idIsMatch: '사용가능한 아이디입니다.',
      emailIsMatch: '이메일 주소 아이디입니다.',
      phoneNumberIsNotFormat: '올바른 휴대폰번호 형식이 아닙니다. ',
    },
    withDrawMoney: {
      noteTitle: '유의사항',
      note_one: '- 1회 출금 상금 최소 5,000원입니다.',
      note_two: '- 1일 기준 50,000원까지 출금 가능합니다.',
    },
    login: {
      idIsNotFound: '존재하지 않는 아이디입니다.',
      passwordIsNotFound: '비밀번호가 일치하지 않습니다.',
      noteInactiveMoreOneYear: `1년 이상 로그인하지 않아 회원님의 계정을 안전하게 보호하기위해 휴면 상태로 자동 전환된 상태입니다. 휴면 상태를 해제하고 서비스를 계속 이용하시겠습니까?`,
      loginFailed: '아이디 또는 비밀번호가 틀렸습니다.',
    },
    signIn: {
      nickname: '닉네임',
      placeholderNickname: '2~10자 이내 국문/영문/숫자',
      id: '아이디',
      placeholderId: '6~16자 이내 영문/영문+숫자',
      password: '비밀번호',
      placeholderPassword: '8~15자 영문/숫자/특수문자 모두 포함',
      confirmPassword: '비밀번호 확인',
      placeholderConfirmPassword: '비밀번호 확인',
      email: '이메일 주소',
      placeholderEmail: '이메일 주소',
      phoneNumber: '휴대폰번호',
      placeholderPhoneNumber: '010-1234-5678',
    },
    game: {
      round_not_exist: '존재하지 않은 대회입니다',
    },
  },
};
